apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-volume-cm
  name: nginx-volume-cm
spec:
  containers:
  - image: nginx
    name: nginx-volume-cm
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
