apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-all-env-cm
  name: nginx-all-env-cm
spec:
  containers:
  - image: nginx
    name: nginx-all-env-cm
    envFrom:
        - configMapRef:
            name: anotherone
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
