apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-env
  name: nginx-env
spec:
  containers:
  - image: nginx
    name: nginx-env
    env:
      - name: option
        valueFrom: 
            configMapKeyRef:
                name: options
                key: var5
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
