apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-volume-cm
  name: nginx-volume-cm
spec:
  containers:
  - image: nginx
    name: nginx-volume-cm
    resources: {}
    volumeMounts:
    - name: config-cm 
      mountPath: /etc/lala
 dnsPolicy: ClusterFirst
 restartPolicy: Never
 volumes:
  - name: config-cm 
    configMap:
      name: cm-volume
status: {}
